### ISSUE TITLE
[Document Update] Version of Cloud Service where this feature is available

### ISSUE THREAD

**Issue by avitripathy01** [AdobeDocs/experience-manager-cloud-service.en#169]
Issue in ./help/assets/dynamic-media/dm-publish-settings.md

 It would be nice to have a note on the documentation page that states on what version of AEM Cloud Service, this feature is available.

**Comment by rickbrough** [comment]
HI Avijit, thank you for your email. We generally do not add to a topic what version of AEM as a Cloud Service that a new feature applies to.
The reason is because AEM as a Cloud Service updates are automatically applied by Adobe to customer accounts; customers are always running the latest version. Plus, the monthly release notes that describe new/updated features and bug fixes, are already associated with a particular version of AEM as a Cloud Service. In this case, the “Configure Dynamic Media Publish Setup for Image Server” feature was mentioned in AEM as a Cloud Service Release Notes for 2021.11.0. (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/release-notes/2021/release-notes-2021-11-0.html?lang=en).


From: Avijit Tripathy ***@***.***>
Date: Friday, February 4, 2022 at 5:29 AM
To: AdobeDocs/experience-manager-cloud-service.en ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AdobeDocs/experience-manager-cloud-service.en] [Document Update] Version of Cloud Service where this feature is available (Issue #169)

Issue in ./help/assets/dynamic-media/dm-publish-settings.md

It would be nice to have a note on the documentation page that states on what version of AEM Cloud Service, this feature is available.

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdobeDocs%2Fexperience-manager-cloud-service.en%2Fissues%2F169&data=04%7C01%7Crbrough%40adobe.com%7C754e61c15fb843c0734508d9e7da041c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637795745825473591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w8XYm%2BZhGv7%2BNeyKzNxJpdsSNlXjKqfZsyCIpPzdcVw%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEVL3WXWPTR7X2PG37TET5LUZPBDHANCNFSM5NRU3KWQ&data=04%7C01%7Crbrough%40adobe.com%7C754e61c15fb843c0734508d9e7da041c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637795745825473591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Tz3HADxYctBycX6XI6XnN9MG8U3m7%2FAECGBPZx%2F%2BBrc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crbrough%40adobe.com%7C754e61c15fb843c0734508d9e7da041c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637795745825473591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nfr4iGZNzR6RKfOUunNRccxIDuz3Gh3e5MDi2u6k4ew%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crbrough%40adobe.com%7C754e61c15fb843c0734508d9e7da041c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637795745825473591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gv5O7G00J22itbYMKU4FRwRUaYuro6UVhBse2SUMEhY%3D&reserved=0>.

**Comment by avitripathy01** [comment]
Thank you Rick for the update.
