### ISSUE TITLE
There should be more information on setting up the port forwards

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#179]
Issue in ./help/security/configuring-advanced-networking.md

Please provide more information and screenshots and steps here on how to set up the port forwards for each environment within the cloud manager UI.

**Comment by aheim0** [comment]
Thank you for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
As of this morning there is new/updated content about configuring CDNs:
- https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/content-delivery/cdn
- https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/content-delivery/cdn-configuring-traffic
- https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/content-delivery/cdn-error-pages

There are also many tutorials on this issue:
- https://experienceleague.adobe.com/en/docs/experience-manager-learn/cloud-service/networking/advanced-networking

We hope this covers your concerns.

**Comment by bohnertchris** [comment]
Directions on how to set up advanced networking for individual environments including screenshots of port forwarding configuration are in the document previously cited under the section **Enabling Advanced Networking Configurations on Environments**.

https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking#enabling

**Comment by aheim0** [comment]
"More" information was requested, and we have provided multiple links. 
Closing issue now.

**Comment by alisonasanchez** [comment]
Actually, it doesn’t.

[Redacted]

**Comment by aheim0** [comment]
@alisonasanchez Thank you for your feedback. Your comment has been redacted in accordance with our policy of avoiding personal/internal information online.

**Comment by bohnertchris** [comment]
Perhaps there is a miscommunication somewhere. As I understand it, the original request of this issue was to provide detailed steps of how to set up port forwarding for an individual environment using the Cloud Manager UI along with screenshots.

The documentation already provides a detailed explanation of what port forwarding is and why one would use it.

https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking#enabling

And the section thereafter then goes on to provide a step-by-step explanation of how to set up advanced networking for an environment along with optional port forwarding, non-proxy hosts, and associated screenshots.

https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking#enabling-ui

This content was introduced with commit e486091 and seems to me to fulfill the original request. Of course if I am misunderstanding the situation or not recognizing the deficiency that this issue attempts to identify, we are happy to expand and improve the docs where necessary, when provided the necessary details. In such case, we would welcome a new issue that explains exactly what is missing and what needs to be changed. Should asynchronous communication via GitHub issue be found inefficient, Adobe colleagues can always reach us at #aem-documentation on Slack.
