### ISSUE TITLE
Is /oak:index immutable or mutable ? 

### ISSUE THREAD

**Issue by kunwarsaluja** [AdobeDocs/experience-manager-cloud-service.en#30]
Issue in help/implementing/developing/introduction/aem-project-content-package-structure.md

Is /oak:index immutable or mutable ?  The documentation extract suggests oak:index  definitions are mutable but the recommended package structure suggests immutable.

and what adds to the confusion,  if they are immutable(which i think they are and i could be wrong), i assumed we might not be  able to change it on runtime via crxde (which i can do(update/delete) and  it doesn’t errors out like it does for  areas under apps and libs)
OR
is it even if i can change directly these from crxde, there won’ be any effect to indexes.

In any case, we should clarify on this and update our documentation for Oak:index guidelines.

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @kunwarsaluja. We will review.

CQDOC-16203

**Comment by bohnertchris** [comment]
Thank you for identifying this point of confusion, @kunwarsaluja. Upon reviewing the content, we have added a section specifically to clarify the status of oak indexes in the package structure and cross-referenced our indexing content. I will allow you to read the revised article, but to summarize:

- `/oak:index` is mutable, but must be deployed as code since the indexes must be in place before content is installed.
- Because they are mutable, the indexes can be changed at runtime for local development instances via CRX DE. However such access is of course not available for production instances.

This change was made as part of commit a59adbb.
